### ISSUE TITLE
No matching indices found: No indices match pattern "logs-endpoint-winevent-sysmon-*"

### ISSUE THREAD

**Issue by mohamedmarrouchi** [Cyb3rWard0g/HELK#241]
Error: No matching indices found: No indices match pattern "logs-endpoint-winevent-sysmon-*"
    at https://172.16.1.156/bundles/commons.bundle.js:3:1321543
    at processQueue (https://172.16.1.156/dlls/vendors.bundle.dll.js:434:199687)
    at https://172.16.1.156/dlls/vendors.bundle.dll.js:434:200650
    at Scope.$digest (https://172.16.1.156/dlls/vendors.bundle.dll.js:434:210412)
    at Scope.$apply (https://172.16.1.156/dlls/vendors.bundle.dll.js:434:213219)
    at done (https://172.16.1.156/dlls/vendors.bundle.dll.js:434:132717)
    at completeRequest (https://172.16.1.156/dlls/vendors.bundle.dll.js:434:136329)
    at XMLHttpRequest.requestLoaded (https://172.16.1.156/dlls/vendors.bundle.dll.js:434:135225)

**Comment by ironpatriot** [comment]
I have the same indices issue.

**Comment by ironpatriot** [comment]
I found it in the documentation to change the WinBeat to 6.xx instead of 7. Logs pour in perfectly after that.

**Comment by Cyb3rWard0g** [comment]
Hey @ironpatriot ! Yes Winlogbeat 7 added some changes to their schema (I dont know why they would do that). More info in this open issue: https://github.com/Cyb3rWard0g/HELK/issues/234 . I am closing this since it is a repeat.
