### ISSUE TITLE
Could not locate that index-pattern-field (Various Patterns)

### ISSUE THREAD

**Issue by denied39** [Cyb3rWard0g/HELK#29]
I just installed HELK yesterday and I am having some issues with index patterns. I have one host reporting to HELK. I am getting results, but there are some fields that don't show, that I'm pretty sure should have data. I'll attach a screenshot of the Sysmon Dashboard. The only issue I can see on the server, is the following:
`root@6c029fbc34fe:/opt/helk/scripts# sudo /opt/helk/kafka/kafka_2.11-1.0.0/bin/zookeeper-shell.sh ls /brokers/ids
Connecting to ls
Exception in thread "main" java.net.UnknownHostException: ls: Temporary failure in name resolution
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
        at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
        at org.apache.zookeeper.ZooKeeperMain.connectToZK(ZooKeeperMain.java:281)
        at org.apache.zookeeper.ZooKeeperMain.<init>(ZooKeeperMain.java:296)
        at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:289)`

I'm not sure how to resolve that issue. I did the install using Ubuntu 16.04 server, and followed the current install instructions on your github page.
![image](https://user-images.githubusercontent.com/1119294/36796231-1a50f044-1c73-11e8-8bfd-1acf41ffbb70.png)

**Comment by Cyb3rWard0g** [comment]
Hey @denied39 ! Can you try something for me? Can you go to the management section of Kibana, select your sysmon index and then click on the refresh button between the start and the trash icons??. Also, can you go to discover and confirm that you are getting logs to the sysmon index?? . Thank you

**Comment by denied39** [comment]
Refreshing the patterns fixed most of the issues. I am still seeing a few errors, but I'm thinking that might be because no matching events have been sent to HELK. I added another host, and I can see both in the sysmon index under discover.

**Comment by Cyb3rWard0g** [comment]
Yeah thats is normal at the beginning. if you dont have the logs that HELK expects then it will show you those error messages. If refreshing the index fixed most of them then it is just an refreshing index step.     I will close this issue but please let me know if you have other issues with it :) Thank you!
