### ISSUE TITLE
Kafka issue | Elastic Issue | Worker Issue  After upgrading to the latest version :( 

### ISSUE THREAD

**Issue by tee2015** [Cyb3rWard0g/HELK#339]
kafka logs :
----------
client has run out of available brokers to talk to (Is your cluster reachable?)
2019-09-18T19:21:00.221+1000	ERROR	pipeline/output.go:100	Failed to connect to kafka : kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
2019-09-18T19:21:00.221+1000	INFO	pipeline/output.go:93	Attempting to reconnect to kafka  with 525 reconnect attempt(s)
2019-09-18T19:21:00.221+1000	INFO	kafka/log.go:53	kafka message: Initializing new client
2019-09-18T19:21:00.221+1000	INFO	kafka/log.go:53	client/metadata fetching metadata for all topics from broker 

elastic:
------

{"type":"log","@timestamp":"2019-09-18T09:30:16Z","tags":["error","task_manager"],"pid":21,"message":"Failed to poll for work: [cluster_block_exception] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)]; :: {\"path\":\"/.kibana_task_manager/_update/Maps-maps_telemetry\",\"query\":{\"if_seq_no\":131,\"if_primary_term\":10,\"refresh\":\"true\"},\"body\":\"{\\\"doc\\\":{\\\"type\\\":\\\"task\\\",\\\"task\\\":{\\\"taskType\\\":\\\"maps_telemetry\\\",\\\"state\\\":\\\"{\\\\\\\"runs\\\\\\\":1,\\\\\\\"stats\\\\\\\":{\\\\\\\"mapsTotalCount\\\\\\\":0,\\\\\\\"timeCaptured\\\\\\\":\\\\\\\"2019-09-04T06:49:56.332Z\\\\\\\",\\\\\\\"attributesPerMap\\\\\\\":{\\\\\\\"dataSourcesCount\\\\\\\":{\\\\\\\"min\\\\\\\":0,\\\\\\\"max\\\\\\\":0,\\\\\\\"avg\\\\\\\":0},\\\\\\\"layersCount\\\\\\\":{\\\\\\\"min\\\\\\\":0,\\\\\\\"max\\\\\\\":0,\\\\\\\"avg\\\\\\\":0},\\\\\\\"layerTypesCount\\\\\\\":{},\\\\\\\"emsVectorLayersCount\\\\\\\":{}}}}\\\",\\\"params\\\":\\\"{}\\\",\\\"attempts\\\":0,\\\"scheduledAt\\\":\\\"2019-09-04T06:49:44.974Z\\\",\\\"runAt\\\":\\\"2019-09-18T09:31:16.819Z\\\",\\\"status\\\":\\\"running\\\"},\\\"kibana\\\":{\\\"uuid\\\":\\\"6a67bed6-5b9b-4b92-b7f6-5bafea39f6d5\\\",\\\"version\\\":7010099,\\\"apiVersion\\\":1}}}\",\"statusCode\":403,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"cluster_block_exception\\\",\\\"reason\\\":\\\"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];\\\"}],\\\"type\\\":\\\"cluster_block_exception\\\",\\\"reason\\\":\\\"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];\\\"},\\\"status\\\":403}\"}"}

Worker : 
------
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: helk-spark-master/172.18.0.6:7077

	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)

	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)

	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)

	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)

	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)

	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)

	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)

	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)

	... 1 more

Caused by: java.net.ConnectException: Connection refused
	... 11 more
19/09/18 08:32:13 INFO Worker: Retrying connection to master (attempt # 1)
19/09/18 08:32:13 INFO Worker: Connecting to master helk-spark-master:7077...
19/09/18 08:32:14 INFO TransportClientFactory: Successfully created connection to helk-spark-master/172.18.0.6:7077 after 25 ms (0 ms spent in bootstraps)
19/09/18 08:32:14 INFO Worker: Successfully registered with master spark://f8ddc59835dc:7077
19/09/18 08:32:14 INFO Worker: WorkerWebUI is available at http://f8ddc59835dc:8080/proxy/worker-20190918083206-172.18.0.12-42950

**Comment by tee2015** [comment]
I Removed the updated Containers after I run the update script , and I run again the compose and build my containers and all sorted out.
