### ISSUE TITLE
Elastalert not generting any alerts and Found out some errors on the Container - Any Suggestions ?

### ISSUE THREAD

**Issue by tee2015** [Cyb3rWard0g/HELK#351]
File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 641, in urlopen, 

    _stacktrace=sys.exc_info()[2]), 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 368, in increment, 

    raise six.reraise(type(error), error, _stacktrace), 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 686, in reraise, 

    raise value, 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 603, in urlopen, 

    chunked=chunked), 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 389, in _make_request, 

    self._raise_timeout(err=e, url=url, timeout_value=read_timeout), 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 307, in _raise_timeout, 

    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value), 

urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='helk-elasticsearch', port=9200): Read timed out. (read timeout=20), 

, 

During handling of the above exception, another exception occurred:, 

, 

Traceback (most recent call last):, 

  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_requests.py", line 124, in perform_request, 

    response = self.session.send(prepared_request, **send_kwargs), 

  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send, 

    r = adapter.send(request, **kwargs), 

  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 529, in send, 

    raise ReadTimeout(e, request=request), 

requests.exceptions.ReadTimeout: HTTPConnectionPool(host='helk-elasticsearch', port=9200): Read timed out. (read timeout=20), 

ERROR:root:Error writing alert info to Elasticsearch: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='helk-elasticsearch', port=9200): Read timed out. (read timeout=20)), 

Traceback (most recent call last):, 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 387, in _make_request, 

    six.raise_from(e, None), 

  File "<string>", line 2, in raise_from, 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 383, in _make_request, 

    httplib_response = conn.getresponse(), 

  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse, 

    response.begin(), 

  File "/usr/lib/python3.6/http/client.py", line 307, in begin, 

    version, status, reason = self._read_status(), 

  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status, 

    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1"), 

  File "/usr/lib/python3.6/socket.py", line 586, in readinto, 

    return self._sock.recv_into(b), 

socket.timeout: timed out, 

, 

During handling of the above exception, another exception occurred:, 

, 

Traceback (most recent call last):, 

  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send, 

    timeout=timeout, 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 641, in urlopen, 

    _stacktrace=sys.exc_info()[2]), 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 368, in increment, 

    raise six.reraise(type(error), error, _stacktrace), 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 686, in reraise, 

    raise value, 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 603, in urlopen, 

    chunked=chunked), 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 389, in _make_request, 

    self._raise_timeout(err=e, url=url, timeout_value=read_timeout), 

  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 307, in _raise_timeout, 

    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value), 

urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='helk-elasticsearch', port=9200): Read timed out. (read timeout=20), 

, 

During handling of the above exception, another exception occurred:, 

, 

Traceback (most recent call last):, 

  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_requests.py", line 124, in perform_request, 

    response = self.session.send(prepared_request, **send_kwargs), 

  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send, 

    r = adapter.send(request, **kwargs), 

  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 529, in send, 

    raise ReadTimeout(e, request=request), 

requests.exceptions.ReadTimeout: HTTPConnectionPool(host='helk-elasticsearch', port=9200): Read timed out. (read timeout=20), 

, 

During handling of the above exception, another exception occurred:, 

, 

Traceback (most recent call last):, 

  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 1603, in writeback, 

    res = self.writeback_es.index(index=index, body=body), 

  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped, 

    return func(*args, params=params, **kwargs), 

  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py", line 364, in index, 

    "POST", _make_path(index, doc_type, id), params=params, body=body, 

  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 350, in perform_request, 

    timeout=timeout,, 

  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_requests.py", line 139, in perform_request, 

    raise ConnectionTimeout("TIMEOUT", str(e), e), 

elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='helk-elasticsearch', port=9200): Read timed out. (read timeout=20)), 

WARNING:apscheduler.executors.default:Run time of job "ElastAlerter.handle_rule_execution (trigger: interval[0:00:30], next run at: 2019-10-01 02:59:43 UTC)" was missed by 0:00:03.483062, 

WARNING:apscheduler.executors.default:Run time of job "ElastAlerter.handle_rule_execution (trigger: interval[0:00:30], next run at: 2019-10-01 02:59:43 UTC)" was missed by 0:00:03.376996,

**Comment by tee2015** [comment]
looks like missing packages any one had this issue before ?

**Comment by Cyb3rWard0g** [comment]
mmmm I wonder is elasticsearch accessible? urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='helk-elasticsearch', port=9200): Read timed out. (read timeout=20),

**Comment by tee2015** [comment]
yeah not accessible true and if u remember I mentioned that I cannot see its exposing port 9200, also I found that the elastic have a red status, still troubleshooting , if this occured before will be appreciated for any guidance cheers.

**Comment by AlfieJ04** [comment]
I rebuilt the HELK system to expose the port 9200 and changed the es_host variable in the elastalert config.yaml to HELKIP and that seems to have resolved it. Get this issue now though:

`WARNING:apscheduler.executors.default:Run time of job "ElastAlerter.handle_rule_execution (trigger: interval[0:00:30], next run at: 2019-10-01 17:10:41 UTC)" was missed by 0:00:02.963583
`

**Comment by neu5ron** [comment]
the missed error is normal, just elastalert catching up

yeah happy to have any help, the curator for logs sounds great - this is the .monitoring indexes correct?
also just fysa currently tracking all the logging filling up disks, trying to figure out how to expose the logs to the host or just use builtin logging in the respective config directories of elk or combo of both

**Comment by AlfieJ04** [comment]
Yea I currently have my test environment setup to delete the following indices:

> logs-endpoint-winevent-
> .monitoring-kibana-
> mitre-attack-
> .monitoring-logstash- 

I'll submit a PR for the Curator addon. I have already Dockerised it and created a Dockerfile etc.
[https://hub.docker.com/r/alfiej04/helk-curator](url)

**Comment by neu5ron** [comment]
all, I will close this - if this is not fixed please reopen and comment with the errors and steps you took.
thanks @AlfieJ04 for the curator stuff too, we will look into this in due time :)
