### ISSUE TITLE
Cannot load winlogbeat using the installation guide

### ISSUE THREAD

**Issue by francescouk** [Cyb3rWard0g/HELK#369]
**Cannot load the winlogbeat using the installation guide**

**Tried to restart the containers but did not resolved the problem. Also tested the connection between servers without any problems. Telnet the port 9092 with sucess**

**How could we replicate the issue?
![image](https://user-images.githubusercontent.com/1994892/67281982-f98c9800-f4a6-11e9-9cb3-a6945ca4a6cd.png)
**

**7.1**

**CentOS 7.6**

** Kafka logs **
** 
![image](https://user-images.githubusercontent.com/1994892/67282773-d8c54200-f4a8-11e9-8d9b-2cc4d68f0164.png) **

**Comment by francescouk** [comment]
For some reason, looks like the kafka is not running so it cannot receive the logs from remote servers:

`[2019-10-22 20:35:18,645] INFO [KafkaServer id=1] started (kafka.server.KafkaServer)
[2019-10-22 20:35:18,647] WARN [SocketServer brokerId=1] Unexpected error from /172.18.0.4; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:424)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:385)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:640)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:561)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:472)
        at kafka.network.Processor.poll(SocketServer.scala:830)
        at kafka.network.Processor.run(SocketServer.scala:730)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by neu5ron** [comment]
@francescouk what operating system is HELK installed on?

**Comment by francescouk** [comment]
CentOS 7.6

**Comment by Cyb3rWard0g** [comment]
@francescouk , I see the `172.18.0.4` IP on the Kafka logs but then I see `10.100.0.154` also in the logs above. Can you share your deployment logs? Also, what is the IP address of your box? You have logs-endpoint-winevent-additional logs being populated. Can you provide a screenshot or sample of the data being populated? You might have modules enabled in your WInlogbeat config?

**Comment by francescouk** [comment]
@Cyb3rWard0g, here is the sample of my winlogbeat.conf:

`winlogbeat.event_logs:
  - name: Application
    ignore_older: 30m
  - name: Security
    ignore_older: 30m
  - name: System
    ignore_older: 30m
  - name: Microsoft-windows-sysmon/operational
    ignore_older: 30m
  - name: Microsoft-windows-PowerShell/Operational
    ignore_older: 30m
    event_id: 4103, 4104
  - name: Windows PowerShell
    event_id: 400,600
    ignore_older: 30m
  - name: Microsoft-Windows-WMI-Activity/Operational
    event_id: 5857,5858,5859,5860,5861
  - name: Microsoft-Windows-TerminalServices-LocalSessionManager/Operational
    event_id: 21,24,25

#----------------------------- Kafka output --------------------------------

#----------------------------- Kafka output --------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  # Place your HELK IP(s) here (keep the port).
  # If you only have one Kafka instance (default for HELK) then remove the 2nd IP that has port 9093
  hosts: ["10.100.0.154:9092"]
  topic: "winlogbeat"
  ############################# HELK Optimizing Latency ######################
  max_retries: 2
  max_message_bytes: 1000000`

It looks like is something to do with CentOS 7.6. I´ve done a second install using ubuntu 18 and is working fine. Used the same step. :(

**Comment by Cyb3rWard0g** [comment]
I wonder if this is related to it: https://github.com/Cyb3rWard0g/HELK/issues/362

**Comment by francescouk** [comment]
@Cyb3rWard0g , I´m not so sure. I still think is related with the heap space in java, as stated above in the logs.

**Comment by neu5ron** [comment]
does winlogbeat show any errors?
i am wondering if there is a crazy large windows event log.
also, what is your sysctl settings for tcp/network? they may need to be tuned/increased

**Comment by neu5ron** [comment]
can you check the output of winlogbeat which should be located in the file:
`"C:\ProgramData\winlogbeat\logs\winlogbeat"`

**Comment by Cyb3rWard0g** [comment]
closing due to inactivity. @francescouk feel free to re-open the issue if you still have issues with Winlogbeat. thank you!
