### ISSUE TITLE
Kafka InvalidReceiveException

### ISSUE THREAD

**Issue by francescouk** [Cyb3rWard0g/HELK#390]
#### Describe the problem
Hello there,
I cannot get winlogbeat to talk with kafka. Only if I set straight to logstash. Can you please try to point me what´s wrong?

This is my output from winlogbeat.exe -e:
```
2020-01-02T14:31:19.865-0300    INFO    beater/winlogbeat.go:169        Stopping Winlogbeat
2020-01-02T14:31:19.874-0300    INFO    beater/eventlogger.go:118       EventLog[Application] Stop processing.
2020-01-02T14:31:19.892-0300    INFO    beater/eventlogger.go:118       EventLog[Security] Stop processing.
2020-01-02T14:31:19.919-0300    INFO    beater/eventlogger.go:118       EventLog[Microsoft-windows-PowerShell/Operational] Stop processing.
2020-01-02T14:31:19.927-0300    INFO    beater/eventlogger.go:118       EventLog[System] Stop processing.
2020-01-02T14:31:20.003-0300    INFO    beater/eventlogger.go:118       EventLog[Microsoft-Windows-Sysmon/Operational] Stop processing.
2020-01-02T14:31:20.288-0300    ERROR   pipeline/output.go:121  Failed to publish events: client is not connected
2020-01-02T14:31:20.288-0300    INFO    pipeline/output.go:95   Connecting to backoff(async(tcp://192.168.0.3:9092))
2020-01-02T14:31:20.288-0300    INFO    pipeline/output.go:105  Connection to backoff(async(tcp://192.168.0.3:9092)) established
2020-01-02T14:31:20.364-0300    ERROR   logstash/async.go:256   Failed to publish events caused by: read tcp 192.168.200.13:54817->172.31.201
2020-01-02T14:31:20.430-0300    ERROR   logstash/async.go:256   Failed to publish events caused by: client is not connected
2020-01-02T14:31:20.631-0300    INFO    beater/eventlogger.go:118       EventLog[Microsoft-Windows-TerminalServices-LocalSessionManager/Opera
2020-01-02T14:31:20.716-0300    INFO    beater/eventlogger.go:118       EventLog[Windows PowerShell] Stop processing.
2020-01-02T14:31:20.716-0300    INFO    [monitoring]    log/log.go:153  Total non-zero metrics  {"monitoring": {"metrics": {"beat":{"cpu":{"s
2020-01-02T14:31:20.716-0300    INFO    [monitoring]    log/log.go:154  Uptime: 6.2216797s
2020-01-02T14:31:20.716-0300    INFO    [monitoring]    log/log.go:131  Stopping metrics logging.
2020-01-02T14:31:20.716-0300    INFO    instance/beat.go:435    winlogbeat stopped.
```

Kafka output:
```
[HELK-DOCKER-INSTALLATION-INFO] Creating Kafka nxlog_mordor Topic..
[2020-01-02 17:17:43,507] WARN [SocketServer brokerId=1] Unexpected error from /192.168.0.5; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 844562432 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:424)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:385)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:640)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:561)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:472)
	at kafka.network.Processor.poll(SocketServer.scala:830)
	at kafka.network.Processor.run(SocketServer.scala:730)
	at java.lang.Thread.run(Thread.java:748)
```

#### Provide the output of the following commands

Get operating system and version
for linux (except Mac) use:  
`cat /etc/os-release`  
for Mac/OSX use:  
`sw_vers`  
Get disk space, memory, processor cores, and docker storage  
`echo -e "\nDocker Space:" && df -h /var/lib/docker; echo -e "\nMemory:" && free -g; echo -e "\nCores:" && getconf _NPROCESSORS_ONLN`  
Get output of the HELK docker containers:  
`docker ps --filter "name=helk"`
```
cat /etc/os-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
```
echo -e "\nDocker Space:" && df -h /var/lib/docker; echo -e "\nMemory:" && free -g; echo -e "\nCores:" && getconf _NPROCESSORS_ONLN

Docker Space:
Filesystem           Size  Used Avail Use% Mounted on
/dev/sda2   		 458G   23G   412G  6% /

Memory:
              total        used        free      shared  buff/cache   available
Mem:             7           5           0           0           1           1
Swap:            3           1           2

Cores:
4
```
```
docker ps --filter "name=helk"

`CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                                              NAMES
4b7180a4c25e        confluentinc/cp-ksql-server:5.1.3                     "/etc/confluent/dockâ€¦"   2 days ago          Up 2 days           0.0.0.0:8088->8088/tcp                                                             helk-ksql-server
afc7d54dbe93        cyb3rward0g/helk-kafka-broker:2.2.0                   "./kafka-entrypoint.â€¦"   2 days ago          Up 35 minutes       0.0.0.0:9092->9092/tcp                                                             helk-kafka-broker
43de93ac0c7a        cyb3rward0g/helk-zookeeper:2.2.0                      "./zookeeper-entrypoâ€¦"   2 days ago          Up 34 minutes       2181/tcp, 2888/tcp, 3888/tcp                                                       helk-zookeeper
7eae45785209        docker_helk-elastalert                                "./elastalert-entrypâ€¦"   2 days ago          Up 2 days                                                                                              helk-elastalert
0c619d403ab1        docker.elastic.co/logstash/logstash:7.1.0             "/usr/share/logstashâ€¦"   2 days ago          Up 2 days           0.0.0.0:3515->3515/tcp, 0.0.0.0:5044->5044/tcp, 0.0.0.0:8531->8531/tcp, 9600/tcp   helk-logstash
14d3d211b3c1        cyb3rward0g/helk-nginx:0.0.7                          "/opt/helk/scripts/nâ€¦"   2 days ago          Up 2 days           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                           helk-nginx
e28261aa7cdf        docker.elastic.co/kibana/kibana:7.1.0                 "/usr/share/kibana/sâ€¦"   2 days ago          Up 2 days           5601/tcp                                                                           helk-kibana
ca747d7cb1ac        docker.elastic.co/elasticsearch/elasticsearch:7.1.0   "/usr/share/elasticsâ€¦"   2 days ago          Up 2 days           9200/tcp, 9300/tcp                                                                 helk-elasticsearch
```

#### Provide the HELK installation logs located at /var/log/helk-install.log if you are having install errors

```
No errors
```

#### What version of HELK are you using

just provide the date you cloned the HELK repo:
```
30 december 2019
```

#### What version of Winlogbeat are you using if you are using Windows/WEF logs

just provide the date you cloned the HELK repo:
```
7.5.0

**Comment by neu5ron** [comment]
can you provide your winlogbeat config? please remove any of your IPs when sending

**Comment by francescouk** [comment]
```
winlogbeat.event_logs:
  - name: Application
    ignore_older: 30m
  - name: Security
    ignore_older: 30m
  - name: System
    ignore_older: 30m
  - name: Microsoft-windows-sysmon/operational
    ignore_older: 30m
  - name: Microsoft-windows-PowerShell/Operational
    ignore_older: 30m
    event_id: 4103, 4104
  - name: Windows PowerShell
    event_id: 400,600
    ignore_older: 30m
  - name: Microsoft-Windows-WMI-Activity/Operational
    event_id: 5857,5858,5859,5860,5861
  - name: Microsoft-Windows-TerminalServices-LocalSessionManager/Operational
    event_id: 21,24,25

#----------------------------- Kafka output --------------------------------

#----------------------------- Kafka output --------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  # Place your HELK IP(s) here (keep the port).
  # If you only have one Kafka instance (default for HELK) then remove the 2nd IP that has port 9093
  hosts: ["192.168.0.10:9092"]
  topic: "winlogbeat"
  ############################# HELK Optimizing Latency ######################
  max_retries: 2
  max_message_bytes: 1000000
``

**Comment by neu5ron** [comment]
is it possible for you to rebuild? there have been a lot of updates to kafka recently that may alleviate this issue.

**Comment by francescouk** [comment]
Ill try today! Thanks
