### ISSUE TITLE
ElastAlert is not working after fresh install

### ISSUE THREAD

**Issue by chinguunhr** [Cyb3rWard0g/HELK#403]
Hi folks,
Elastalert is not working properly. Here is elast alert log. 

`ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, 'illegal_argument_exception', 'mapper [match_body.z_logstash_pipeline] of different ty
pe, current_type [keyword], merged_type [long]')                                                                                                              
Traceback (most recent call last):                                                                                                                            
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 1603, in writeback                                  
    res = self.writeback_es.index(index=index, body=body)                                                                                                     
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped                                                           
    return func(*args, params=params, **kwargs)                                                                                                               
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py", line 364, in index                                                          
    "POST", _make_path(index, doc_type, id), params=params, body=body                                                                                         
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 350, in perform_request                                                      
    timeout=timeout,                                                                                                                                          
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_requests.py", line 156, in perform_request                                       
    self._raise_error(response.status_code, raw_data)                                                                                                         
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py", line 181, in _raise_error                                                   
    status_code, error_message, additional_info                                                                                                               
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'mapper [match_body.z_logstash_pipeline] of different type, current_typ
e [keyword], merged_type [long]')               `

> `ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, 'illegal_argument_exception', 'mapper [match_body.z_logstash_pipeline] of different ty
pe, current_type [keyword], merged_type [long]')                                                                                                              
Traceback (most recent call last):                                                                                                                            
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 1603, in writeback                                  
    res = self.writeback_es.index(index=index, body=body)                                                                                                     
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped                                                           
    return func(*args, params=params, **kwargs)                                                                                                               
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py", line 364, in index                                                          
    "POST", _make_path(index, doc_type, id), params=params, body=body                                                                                         
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 350, in perform_request                                                      
    timeout=timeout,                                                                                                                                          
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_requests.py", line 156, in perform_request                                       
    self._raise_error(response.status_code, raw_data)                                                                                                         
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py", line 181, in _raise_error                                                   
    status_code, error_message, additional_info                                                                                                               
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'mapper [match_body.z_logstash_pipeline] of different type, current_typ
e [keyword], merged_type [long]')               `

**Comment by neu5ron** [comment]
had HELK every previously been installed on this machine?

**Comment by chinguunhr** [comment]
No. I had installed HELK on new system.

**Comment by neu5ron** [comment]
can you send the output of the following command, note it must be run with in the HELK directory.
`cd HELK && cat .git/refs/heads/master`

**Comment by chinguunhr** [comment]
cat .git/refs/heads/master 
fa329ccdb168e6735791649ea848be577f34373c


Thank you in advance.

**Comment by neu5ron** [comment]
can you reclone the repo and try? I pushed a few updates today. You will first need to run `sudo /bin/sh HELK/docker/helk_remove_containers.sh`

**Comment by chinguunhr** [comment]
After did what you suggested, its still now working. Here is log
File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 370, in index
    "POST", _make_path(index, doc_type, id), params=params, body=body
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_requests.py", line 160, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'mapper [match_body.z_logstash_pipeline] of different type, current_type [keyword], merged_type [long]')
WARNING:elasticsearch:POST http://helk-elasticsearch:9200/elastalert_status/_doc [status:400 request:0.004s]
ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, 'illegal_argument_exception', 'mapper [match_body.z_logstash_pipeline] of different type, current_type [keyword], merged_type [long]')
Traceback (most recent call last):


  File "/usr/local/lib/python3.5/dist-packages/elastalert-0.2.1-py3.5.egg/elastalert/elastalert.py", line 1615, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 370, in index
    "POST", _make_path(index, doc_type, id), params=params, body=body
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_requests.py", line 160, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'mapper [match_body.z_logstash_pipeline] of different type, current_type [keyword], merged_type [long]')


 cat .git/refs/heads/master
b4d8d112843d4760f6ae03c79500c6f79eeea682

**Comment by neu5ron** [comment]
there has to be a elasticsearch instance laying around somewhere.
run the remove containers script again, then run
`docker volume prune`
then rebuild.. I really havent seen this error your having since mid 2019. I definitely believe you, im just scratching my head 🙃

**Comment by chinguunhr** [comment]
:) . thank you for your effort.

**Comment by chinguunhr** [comment]
it works now.
