### ISSUE TITLE
Error Elastalert new installation 

### ISSUE THREAD

**Issue by francescouk** [Cyb3rWard0g/HELK#442]
#### Describe the problem
```
Starting Elastalert..
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/elastalert-0.2.1-py3.5.egg/elastalert/loaders.py", line 123, in load
    raise EAException('Duplicate rule named %s' % (rule['name']))
elastalert.util.EAException: Duplicate rule named Judgement-Panda-Exfil-Activity_0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert')()
  File "/usr/local/lib/python3.5/dist-packages/elastalert-0.2.1-py3.5.egg/elastalert/elastalert.py", line 2050, in main
    client = ElastAlerter(args)
  File "/usr/local/lib/python3.5/dist-packages/elastalert-0.2.1-py3.5.egg/elastalert/elastalert.py", line 140, in __init__
    self.rules = self.rules_loader.load(self.conf, self.args)
  File "/usr/local/lib/python3.5/dist-packages/elastalert-0.2.1-py3.5.egg/elastalert/loaders.py", line 125, in load
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file rules/sigma_win_apt_judgement_panda_gtr19.yml: Duplicate rule named Judgement-Panda-Exfil-Activity_0
```
#### Provide the output of the following commands

Get operating system and version
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Get disk space, memory, processor cores, and docker storage  
```
Docker Space:
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       246G   14G  220G   6% /

Memory:
              total        used        free      shared  buff/cache   available
Mem:             11           9           0           0           1           1
Swap:             3           0           3

Cores:
8
```

Get output of the HELK docker containers:  
```
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                                              NAMES
0e28bee9caab        confluentinc/cp-ksql-cli:5.1.3                        "/bin/sh"                11 minutes ago      Up 11 minutes                                                                                          helk-ksql-cli
c8021086fa6c        confluentinc/cp-ksql-server:5.1.3                     "/etc/confluent/dock…"   11 minutes ago      Up 11 minutes       0.0.0.0:8088->8088/tcp                                                             helk-ksql-server
d07986d58c26        otrf/helk-kafka-broker:2.3.0                          "./kafka-entrypoint.…"   11 minutes ago      Up 11 minutes       0.0.0.0:9092->9092/tcp                                                             helk-kafka-broker
c8b67073d1cc        otrf/helk-elastalert:0.2.6                            "./elastalert-entryp…"   11 minutes ago      Up 16 seconds                                                                                          helk-elastalert
53243ef141d8        otrf/helk-zookeeper:2.3.0                             "./zookeeper-entrypo…"   11 minutes ago      Up 11 minutes       2181/tcp, 2888/tcp, 3888/tcp                                                       helk-zookeeper
c9b4ee1d5959        otrf/helk-logstash:7.5.2.2                            "/usr/share/logstash…"   11 minutes ago      Up 11 minutes       0.0.0.0:3515->3515/tcp, 0.0.0.0:5044->5044/tcp, 0.0.0.0:8531->8531/tcp, 9600/tcp   helk-logstash
32d6fda8b5d6        otrf/helk-nginx:0.0.8                                 "/opt/helk/scripts/n…"   11 minutes ago      Up 11 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                           helk-nginx
4df19cc082e2        docker.elastic.co/kibana/kibana:7.5.2                 "/usr/share/kibana/s…"   11 minutes ago      Up 11 minutes       5601/tcp                                                                           helk-kibana
b41bbd762942        docker.elastic.co/elasticsearch/elasticsearch:7.5.2   "/usr/share/elastics…"   11 minutes ago      Up 11 minutes       9200/tcp, 9300/tcp                                                                 helk-elasticsearch
```

#### What version of HELK are you using

run the command from within the HELK root directory `cat .git/refs/heads/master`  
```
e819bc892a1fe3830f62ec4d33eeaa7f43eb2c51
```

Place the date here
```
24/03/2020
```

##### What steps did you take trying to fix the issue
**Trying to add another id version! No luck**

![image](https://user-images.githubusercontent.com/1994892/77462668-34db1c00-6de3-11ea-9606-3673f6b13677.png)

**Comment by Relkci** [comment]
Can confirm this is an issue.  First noticed this last weekend.  Can also provide logs if needed, ultimately same output as above however.

**Comment by justintime** [comment]
In the script `pull-sigma.sh`, it grabs two yml files that contain the same rule name.  Here's the colliding files:
```
sigma_win_apt_bear_activity_gtr19.yml
sigma_win_apt_judgement_panda_gtr19.yml
```

**Comment by justintime** [comment]
I think I see what happened.  [In a commit made Feb 1](https://github.com/Neo23x0/sigma/commit/03ecb3b8dcbbb3f77c3445a11a04395d43926cc1), there was a refactor in sigma.  The result moved these 2 files into the same directory:
[Bear](https://github.com/Neo23x0/sigma/blob/aa8a0f5e1f8b20bc1970462f65140f1666ad8e20/rules/windows/process_creation/win_apt_bear_activity_gtr19.yml)
[Panda](https://github.com/Neo23x0/sigma/blob/aa8a0f5e1f8b20bc1970462f65140f1666ad8e20/rules/windows/process_creation/win_apt_judgement_panda_gtr19.yml)

Those two yml files have the same Title property.  A change in the `pull-sigma.sh` script would be a hack, the proper way to fix this is to probably ask for a title change in one of the files in sigma.

**Comment by justintime** [comment]
@Relkci looks like they merged the  pull request.  I don't have access to the lab any more, can you verify if this fixed the problem?

**Comment by rev10d** [comment]
This is fixed at the Sigma repos, but has not been pulled in to the sigma.git. Collisions still exist in HELK's opt / sigma / rules. Thus, during the docker install process, the title collision occurs and Elastalert fails. 

Same title here: 
https://github.com/Cyb3rWard0g/sigma/blob/master/rules/windows/process_creation/win_apt_judgement_panda_gtr19.yml

And here:
https://github.com/Cyb3rWard0g/sigma/blob/master/rules/windows/process_creation/win_apt_bear_activity_gtr19.yml

I think a pull of the Sigma repo back in to HELK will solve this issue.

**Comment by Cyb3rWard0g** [comment]
Thank you all! I appreciate all the information and the fix for it 🍻 PR merged https://github.com/Cyb3rWard0g/sigma/pull/11 . Let me know if that fixes the issue. Thank you all!

**Comment by rev10d** [comment]
Fixed! Fixed! Yeah!

Thank you thank you!!!

**Comment by francescouk** [comment]
Fixed for me ass well! :)

Thank you!
